  - alias: Kitchen Spots Double-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.kitchen_spots
        scene_id: 14
    action:
      service: script.toggle_downstairs_lights

  - alias: Living Room Spots Double-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.living_room_spots
        scene_id: 14
    action:
      service: script.toggle_living_room_lights

  - alias: Fire Place Spots Double-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.fireplace_spots
        scene_id: 14
    action:
      service: light.toggle
      entity_id: light.oil_drum_light

  - alias: Mid Room Spots Double-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.mid_room_spots
        scene_id: 14
    action:
      service: script.toggle_downstairs_lights

  - alias: Dinner Table Light Double-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.dinner_table_lights
        scene_id: 14
    action:
      service: switch.toggle
      entity_id: switch.lantern

  - alias: Bedroom Double-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_spots
        scene_id: 14
    action:
      service_template: >
        homeassistant.turn_{% if is_state('group.bedroom_lights', 'on') %}off{% else %}on{% endif %}
      entity_id: group.bedroom_lights

  - alias: Room Charlotte Double-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.room_charlotte_light
        scene_id: 14
    action:
      service: script.toggle_charlotte_brightness

  - alias: Bedroom 2nd Button Single-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_spots
        scene_id: 26
    action:
      service: light.toggle
      entity_id: light.nightlight_marvin

  - alias: Bedroom 2nd Button Triple-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_spots
        scene_id: 25
    action:
     service: homeassistant.turn_off
     entity_id: group.all_lights

  - alias: Office Double-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.office_spots
        scene_id: 14
    action:
      service_template: >
        homeassistant.turn_{% if is_state('group.office_lights', 'on') %}off{% else %}on{% endif %}
      entity_id: group.office_lights

  - alias: Hall Light Double-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.hall_light
        scene_id: 1
    action:
      service: script.toggle_hall_lights

  - alias: Hallway Light Double-Click
    initial_state: true
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.hallway_light
        scene_id: 14
    action:
      service: script.toggle_hall_lights

 #      - service: notify.marvin_telegram
 #       data:
 #         message: 'Lights toggled'

  - alias: Telegram start
    initial_state: false
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/start'
    action:
      service: notify.marvin_telegram
      data:
        message: 'commands'
        data:
          keyboard:
            - '/lights'

  - alias: Telegram light control
    initial_state: false
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/lights'
    action:
      service: homeassistant.toggle
      entity_id:
        - group.living_room_lights

  - alias: Away Mode Lights ON
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/15'
    condition:
      - condition: state
        entity_id: input_boolean.away
        state: 'on'
      - condition: sun
        after: sunset
      - condition: state
        entity_id: group.living_room_lights
        state: 'off'
    action:
      - delay: '00:{{ range(1,14) | random | int }}:00'
      - condition: state
        entity_id: input_boolean.away
        state: 'on'
      - service: scene.turn_on
        entity_id: scene.livingroom_evening
      - service: notify.marvin_telegram
        data:
          message: 'Away mode: Lights on'

  - alias: Away Mode Lights OFF
    initial_state: true
    trigger:
      platform: time
      at: '23:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.away
        state: 'on'
      - condition: state
        entity_id: group.downstairs_lights
        state: 'on'
    action:
      - delay: '00:{{ range(0,30) | random | int }}:00'
      - condition: state
        entity_id: input_boolean.away
        state: 'on'
      - service: homeassistant.turn_off
        entity_id: group.downstairs_lights
      - service: notify.marvin_telegram
        data:
          message: 'Away mode: Lights off'

  - alias: 'Away Mode On'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.all_persons
        from: 'home'
        to: 'not_home'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.away
      - service: notify.marvin_telegram
        data:
          message: 'Set Away mode: ON'

  - alias: 'Away Mode Off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.all_persons
        from: 'not_home'
        to: 'home'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.away
      - service: notify.marvin_telegram
        data:
          message: 'Set Away mode: OFF'
