  - alias: Kitchen Spots Double-Click
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.kitchen_spots
        scene_id: 14
    action:
      service: script.toggle_kitchen_lights

  - alias: Living Room Spots Double-Click
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.living_room_spots
        scene_id: 14
    action:
      service: script.toggle_living_room_lights

  - alias: Mid Room Spots Double-Click
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.mid_room_spots
        scene_id: 14
    action:
      service: script.toggle_downstairs_lights

  - alias: Bedroom Double-Click
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_spots
        scene_id: 14
    action:
      service_template: >
        homeassistant.turn_{% if is_state('group.bedroom_lights', 'on') %}off{% else %}on{% endif %}
      entity_id: group.bedroom_lights

  - alias: Bedroom 2nd Button Single-Click
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_spots
        scene_id: 26
    action:
      service: light.toggle
      entity_id: light.nightlight_marvin

  - alias: Bedroom 2nd Button Triple-Click
    trigger:
      platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.bedroom_spots
        scene_id: 25
    action:
     service: homeassistant.turn_off
     entity_id: group.all_lights

 #      - service: notify.marvin_telegram
 #       data:
 #         message: 'Lights toggled'

  - alias: Telegram start
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/start'
    action:
      service: notify.marvin_telegram
      data:
        message: 'commands'
        data:
          keyboard:
            - '/lights'

  - alias: Telegram light control
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/lights'
    action:
      service: homeassistant.toggle
      entity_id:
        - group.living_room_lights
