homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

logger:
  default: warning
  logs:
    homeassistant.components.device_tracker.nmap_tracker: warning

recorder:
  purge_keep_days: 31
  db_url: !secret recorder_url

zwave:
  usb_path: /dev/zwave
  #device_config: !include zwave_device_config.yaml
  #network_key: !secret zwave_network_key

# Show links to resources in log and frontend
# introduction:

system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: !secret http_base_url
  trusted_networks:
    - !secret network_subnet
  trusted_proxies:
    - !secret server_ip
    - !secret router_ip
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'temperature'
      - 'humidity'
      - 'target'

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  entity_config: !include google_assistant_entity_config.yaml

tradfri:
  host: !secret tradfri_ip
  allow_tradfri_groups: false

googlehome:
  devices:
    - host: !secret googlehome_ip
      track_alarms: true

# Weather prediction
weather:
  - platform: buienradar
    name: Eemnes

# Sensors
sensor:
  - platform: fitbit
    clock_format: 24H
    monitored_resources:
      - "body/weight"
      - "activities/heart"
      - "activities/steps"
      - "devices/battery"
      - "sleep/efficiency"
  # TODO: Enable P1
  # - platform: dsmr
  #   port: /dev/p1
  #   dsmr_version: 5

device_tracker:
  - platform: nmap_tracker
    hosts:
      - !secret network_subnet
    exclude:
      - !secret server_ip
      - !secret router_ip
      - !secret ap_ip
      - !secret hass_ip

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_token
    allowed_chat_ids:
      - !secret telegram_marvin_chat_id

notify:
  - name: marvin_telegram
    platform: telegram
    chat_id: !secret telegram_marvin_chat_id

influxdb:
  host: !secret server_ip
  port: !secret influxdb_port
  database: homeassistant
  tags:
    source: hass

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    aliases:
      29eefd60acc97fed992eb7d0fe78d0d2: Living Room speaker
      ccc59223dd04f56822bf1aa4b919be6e: RonkCast
      57e3675976d730e4c40812a0c378e98108243361: Marvin Phone
      65446b7218f8ab1091cc2ae4f6e0cc94c33e3bb1: Marvin Ubuntu

input_boolean:
  away:
    name: Away mode
    icon: mdi:exit-run

person: !include persons.yaml
group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
