light.living_room_spots_level_2:
  ignored: true
  polling_intensity: 0
sensor.living_room_spots_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.living_room_spots_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.living_room_spots_energy:
  ignored: true
  polling_intensity: 0
sensor.living_room_spots_exporting:
  ignored: true
  polling_intensity: 0
sensor.living_room_spots_heat:
  ignored: true
  polling_intensity: 0
sensor.living_room_spots_power_2:
  ignored: true
  polling_intensity: 0
sensor.living_room_spots_power:
  ignored: true
  polling_intensity: 0
sensor.living_room_spots_power_management:
  ignored: true
  polling_intensity: 0
sensor.living_room_spots_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.living_room_spots_system:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_spots_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_spots_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_spots_energy:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_spots_exporting:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_spots_heat:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_spots_power:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_spots_power_2:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_spots_power_management:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_spots_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_spots_system:
  ignored: true
  polling_intensity: 0
